name: Daily Booking

on:
  schedule:
    - cron: "29 20 * * *"   # 05:59 AM IST
  workflow_dispatch:

jobs:
  run-booking:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      FLAT_Y:  ${{ secrets.FLAT_Y }}
      FLAT_D:  ${{ secrets.FLAT_D }}
      FLAT_SD: ${{ secrets.FLAT_SD }}
      FLAT_SY: ${{ secrets.FLAT_SY }}
      FLAT_M:  ${{ secrets.FLAT_M }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install requests pytz

      - name: Run Booking Scheduler
        run: python scheduler.py

      - name: Upload Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: booking-log
          path: booking_log.txt
