name: Daily Booking

on:
  schedule:
    #- cron: "29 20 * * *"   # 05:59 AM IST daily
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-booking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Booking Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          python scheduler.py

      - name: Upload Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: booking-log
          path: booking_log.txt
